_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NMS_THRESH_TEST: 0.95
    SCORE_THRESH_TEST: 0.5
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (30000, 45000)
  MAX_ITER: 50000
  BASE_LR: 0.02
INPUT:
  MIN_SIZE_TRAIN: (640, 864)
  MIN_SIZE_TRAIN_SAMPLING: "range"
  MAX_SIZE_TRAIN: 1440
  CROP:
    ENABLED: True
TEST:
  AUG:
    ENABLED: True
DATASETS:
  TRAIN: ("demo_train",)
  TEST: ("demo_val",)
OUTPUT_DIR: "../../data/DemoDataset/detectron2_prediction"
