_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: '/home/qiu/Downloads/models/detectron2/detectron2_mask_rcnn_fpn_3x_pre.pkl'
  MASK_ON: True
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 1
  STEPS: (30000, 45000)
  MAX_ITER: 50000
  BASE_LR: 0.02

